Update Unicorn config

diff --git a/packer/web/unicorn/unicorn_events b/packer/web/unicorn/unicorn_events
--- a/packer/web/unicorn/unicorn_events
+++ b/packer/web/unicorn/unicorn_events
@@ -6,25 +6,22 @@
 # Required-Stop:     $all
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: starts the unicorn app server
-# Description:       starts unicorn using start-stop-daemon
+# Short-Description: starts the unicorn web server
+# Description:       starts unicorn
 ### END INIT INFO
 
-set -e
+set -e # fail due to return codes
+set -u # fail due to undefined variables
 
-USAGE="Usage: $0 <start|stop|restart|upgrade|rotate|force-stop>"
-
-# app settings
+# PATH="/home/$USER/.rbenv/shims:/home/$USER/.rbenv/bin:$PATH" # potentially useful
+# ENV="production"
 USER="ubuntu"
+TIMEOUT=60
 APP_NAME="events"
-APP_ROOT="/home/$USER/$APP_NAME/current"
-ENV="production"
-
-# environment settings
-PATH="/home/$USER/.rbenv/shims:/home/$USER/.rbenv/bin:$PATH"
-CMD="cd $APP_ROOT && bundle exec unicorn -c config/unicorn.rb -E $ENV -D"
-PID="$APP_ROOT/shared/pids/unicorn.pid"
-OLD_PID="$PID.oldbin"
+APP_ROOT="/home/$USER/$APP_NAME"
+PID_DIR=$APP_ROOT/shared/pids
+PID=$PID_DIR/unicorn.pid
+CMD="cd $APP_ROOT/current;  bundle exec unicorn -D -c config/unicorn.rb" # dont pass -E $ENV , let's see if it works
 
 # make sure the app exists
 cd $APP_ROOT || exit 1
@@ -33,37 +30,43 @@ sig () {
   test -s "$PID" && kill -$1 `cat $PID`
 }
 
-oldsig () {
-  test -s $OLD_PID && kill -$1 `cat $OLD_PID`
+workersig () {
+  workerpid="$PID_DIR/unicorn.$2.pid"
+  
+  test -s "$workerpid" && kill -$1 `cat $workerpid`
 }
 
-case $1 in
-  start)
-    sig 0 && echo >&2 "Already running" && exit 0
-    echo "Starting $APP_NAME"
-    su - $USER -c "$CMD"
-    ;;
-  stop)
-    echo "Stopping $APP_NAME"
-    sig QUIT && exit 0
-    echo >&2 "Not running"
-    ;;
-  force-stop)
-    echo "Force stopping $APP_NAME"
-    sig TERM && exit 0
-    echo >&2 "Not running"
-    ;;
-  restart|reload|upgrade)
-    sig USR2 && echo "reloaded $APP_NAME" && exit 0
-    echo >&2 "Couldn't reload, starting '$CMD' instead"
-    $CMD
-    ;;
-  rotate)
-    sig USR1 && echo rotated logs OK && exit 0
-    echo >&2 "Couldn't rotate logs" && exit 1
-    ;;
-  *)
-    echo >&2 $USAGE
-    exit 1
-    ;;
+run () {
+  su - $USER -c "$CMD"
+}
+
+case "$1" in
+start)
+  sig 0 && echo >&2 "Already running" && exit 0
+  run
+  ;;
+stop)
+  sig QUIT && exit 0
+  echo >&2 "Not running"
+  ;;
+force-stop)
+  sig TERM && exit 0
+  echo >&2 "Not running"
+  ;;
+kill-worker)
+  workersig QUIT $2 && exit 0
+  echo >&2 "Worker not running"
+  ;;
+restart)
+  sig USR2 && echo reloaded OK && exit 0
+  echo >&2 "Couldn't reload, starting '$CMD' instead"
+  run
+  ;;
+reopen-logs)
+  sig USR1
+  ;;
+*)
+  echo >&2 "Usage: $0 <start|stop|force-stop|kill-worker|restart|reopen-logs>"
+  exit 1
+  ;;
 esac
